// Message Types
const INITIALIZE = 'INITIALIZE';
const NODE_CLICKED = 'NODE_CLICKED';
const VALID_START_NODE = 'VALID_START_NODE';
const INVALID_START_NODE = 'INVALID_START_NODE';
const VALID_END_NODE = 'VALID_END_NODE';
const INVALID_END_NODE = 'INVALID_END_NODE';
const GAME_OVER = 'GAME_OVER';
const ERROR_MSG = 'ERROR';
const UPDATE_TEXT = 'UPDATE_TEXT';

module.exports.messageTypes = {
    INITIALIZE,
    NODE_CLICKED,
    VALID_END_NODE,
    VALID_START_NODE,
    INVALID_END_NODE,
    INVALID_START_NODE,
    GAME_OVER,
    ERROR_MSG,
    UPDATE_TEXT
}